Definindo padrão das telas de listagem
PedroDCN/avaliador-disciplinas pull request #12
Opened 2022-03-10 23:16 UTC by joao-dantas31

2022-03-10 23:21 UTC, joao-dantas31 commented
Bloqueado enquanto o https://github.com/PedroDCN/avaliador-disciplinas/pull/10 não for mergeado.

2022-03-13 11:50 UTC, MelquiSilva approved these changes

2022-03-14 00:44 UTC, davibss commented on AvaliadorDisciplinas.FRONTEND/src/components/ButtonWithIcon/ButtonWithIcon.module.css
> +.transparent {
O botão poderia manter o **cursor: pointer** mesmo estando no modo "transparente".

2022-03-14 00:45 UTC, davibss commented on AvaliadorDisciplinas.FRONTEND/src/components/DataList/DataList.module.css
> +  text-align: center;
Acho que esse **text-align** pode ser removido.

2022-03-14 00:47 UTC, davibss commented on AvaliadorDisciplinas.FRONTEND/src/components/Dropdown/Dropdown.module.css
> +  border-radius: 1em;
Acho que poderia ser:
```suggestion
  border-radius: 1rem;
```

2022-03-14 00:50 UTC, davibss commented on AvaliadorDisciplinas.FRONTEND/src/pages/Disciplina/Disciplina.module.css
> +.container .content .indexContent span {
Acho que esse **span** pertence mais a classe `.indexContainer` do que a `.indexContent`, talvez seria melhor passar essa estilização para a `.indexContainer span`.

2022-03-14 00:52 UTC, davibss commented on AvaliadorDisciplinas.FRONTEND/src/pages/Disciplina/index.jsx
> +            transparent
Aqui no navegador esse atributo deu erro no console, porque ele não identifica esse atributo como boolean, o erro é resolvido se colocar desta forma:
```suggestion
            transparent="true"
```

2022-03-14 00:53 UTC, davibss commented on AvaliadorDisciplinas.FRONTEND/src/pages/Disciplina/index.jsx
> +            onClick={() => console.log(item.nome)}
Acho que esse `console.log` pode ser removido.

2022-03-14 01:01 UTC, davibss approved these changes
- sugestões:
   - renderItem() poderia ser um componente separado, com seu próprio css, para não se misturar com o css da página de disciplinas
   - aumentar o paddingTop e paddingBottom no texto do filtro e no dropdown do filtro para o  texto ficar mais espaçado
   - o tamanho da fonte usada na lista pode ser menor para ficar proporcional a página
   - o border-radius do filtro e do dropdown poderia ser um pouco menor
  
 - discutir em reunião:
   - a página Disciplina está recarregando o menu lateral

2022-03-14 14:45 UTC, Bruno-af requested changes

2022-03-14 14:45 UTC, Bruno-af commented on AvaliadorDisciplinas.FRONTEND/src/pages/Disciplina/Disciplina.module.css
> +  background: #189ab4;
Adicionar ao global.css para uso em outras telas

2022-03-14 14:45 UTC, Bruno-af commented on AvaliadorDisciplinas.FRONTEND/src/pages/Disciplina/Disciplina.module.css
> +  color: #ffffff;
usar var(--white)

2022-03-14 19:17 UTC, Bruno-af commented on AvaliadorDisciplinas.FRONTEND/src/components/Dropdown/Dropdown.module.css
> +  color: #1e1e1e;
utilizar cores pelo global.css

2022-03-16 13:38 UTC, joao-dantas31 commented on AvaliadorDisciplinas.FRONTEND/src/components/ButtonWithIcon/ButtonWithIcon.module.css
> +.transparent {
Corrigido!

2022-03-16 13:38 UTC, joao-dantas31 commented on AvaliadorDisciplinas.FRONTEND/src/components/Dropdown/Dropdown.module.css
> +  border-radius: 1em;
Corrigido!

2022-03-16 13:38 UTC, joao-dantas31 commented on AvaliadorDisciplinas.FRONTEND/src/pages/Disciplina/Disciplina.module.css
> +.container .content .indexContent span {
Corrigido!

2022-03-16 13:38 UTC, joao-dantas31 commented on AvaliadorDisciplinas.FRONTEND/src/pages/Disciplina/index.jsx
> +            transparent
Corrigido!

2022-03-16 13:43 UTC, joao-dantas31 commented on AvaliadorDisciplinas.FRONTEND/src/components/Dropdown/Dropdown.module.css
> +  color: #1e1e1e;
Corrigido!

2022-03-16 13:44 UTC, joao-dantas31 commented on AvaliadorDisciplinas.FRONTEND/src/pages/Disciplina/Disciplina.module.css
> +  color: #ffffff;
Corrigido!

2022-03-16 19:31 UTC, Bruno-af approved these changes

2022-03-16 20:48 UTC, merged