Toques finais de Feedback e Student
PedroDCN/avaliador-disciplinas pull request #30
Opened 2022-03-21 22:34 UTC by Rodrigo-Torres-Meira

2022-03-21 22:47 UTC, Juhrer approved these changes

2022-03-21 23:47 UTC, merged

2022-03-21 23:48 UTC, HolliverCosta requested changes

2022-03-21 23:48 UTC, HolliverCosta commented on AvaliadorDisciplinas.API/src/main/java/com/engSoft/controllers/FeedbackController.java
> +            return ErroSemester.erroSemesterNotFound();
aqui é erro course

2022-03-22 00:00 UTC, Rodrigo-Torres-Meira commented on AvaliadorDisciplinas.API/src/main/java/com/engSoft/controllers/FeedbackController.java
> +            return ErroSemester.erroSemesterNotFound();
vou ajeitar aq e fzr push direto pro develop